service: focus-application

provider:
    name: aws
    runtime: nodejs14.x
    region: us-east-1
    timeout: 900
    memorySize: 3008

    # Accept stage from command line, defaults to dev
    # - Should be EITHER prod or dev
    stage: ${opt:stage, 'dev'}

functions:
    server:
        url:
            cors: true
        handler: dist/server/handler.server
        events:
            # For our Schedule jobs, we only want to deploy the schedules
            # in our Production deployment stage

            - schedule:
                  name: Schedule_ElasticSearchSyncJob-${opt:stage, 'dev'}
                  description: "An event scheduled to run the ElasticSearchSyncJob once each day at 1 AM EST/5 AM UTC"
                  rate: cron(0 5 * * ? *)
                  enabled: true
                  input:
                      path: "/api/job/ElasticSearchSyncJob"
                      httpMethod: "POST"

            - schedule:
                  name: Schedule_BookmarkDeliveryJob-${opt:stage, 'dev'}
                  description: "An event scheduled to run the BookmarkDeliveryJob once every 3 hours"
                  rate: cron(0 */3 * * ? *)
                  enabled: true
                  input:
                      path: "/api/job/BookmarkDeliveryJob"
                      httpMethod: "POST"

            - schedule:
                  name: Schedule_StoryDeliveryJob-${opt:stage, 'dev'}
                  description: "An event scheduled to run the StoryDeliveryJob once every 4 hours"
                  rate: cron(0 */4 * * ? *)
                  enabled: true
                  input:
                      path: "/api/job/StoryDeliveryJob"
                      httpMethod: "POST"

            - schedule:
                  name: Schedule_StorySyncJob-${opt:stage, 'dev'}
                  description: "An event scheduled to run the StorySyncJob once each day at 2 AM EST/6 AM UTC"
                  rate: cron(0 6 * * ? *)
                  enabled: true
                  input:
                      path: "/api/job/StorySyncJob"
                      httpMethod: "POST"

            - schedule:
                  name: Schedule_SessionClearJob-${opt:stage, 'dev'}
                  description: "An event scheduled to run the SessionClearJob once every 3 days at 12 AM EST/4 AM UTC"
                  rate: cron(0 4 */3 * ? *)
                  enabled: false
                  input:
                      path: "/api/job/SessionClearJob"
                      httpMethod: "POST"

package:
    patterns:
        - "!./**"
        - "dist/**"
        - "package.json"
        - "node_modules/**"
        - "!node_modules/.prisma/client/libquery_engine-*"
        - "node_modules/.prisma/client/libquery_engine-rhel-*"
        - "!node_modules/prisma/libquery_engine-*"
        - "!node_modules/@prisma/engines/**"
