INSERT INTO public.translations (id,parent_id,screen_text,english_translation,chinese_translation,french_translation,german_translation,italian_translation,japanese_translation,korean_translation,russian_translation,spanish_translation,created_at,updated_at,display_order,unique_identifier) VALUES
	 (154,103,'the Barnes?','the Barnes?','巴恩斯？','les Barnes?','die Barnes?',' il Barnes?','バーンズ？','반즈?','Барнс?','los barnes?','2019-02-06 17:33:14','2019-02-13 20:31:52',NULL,'text_2'),
	 (106,103,'No','No','没有','Non','Nein','No','いいえ','아니','нет','No','2019-01-30 11:07:43','2019-02-06 17:33:14',NULL,'text_4'),
	 (105,103,'Yes','Yes','是','Oui','Ja','sì','はい','예','да','Sí','2019-01-30 11:07:43','2019-02-06 17:33:14',NULL,'text_3'),
	 (155,111,'Disclaimer','Disclaimer','放弃','Avertissement','Haftungsausschluss','disconoscimento','免責事項','기권','отказ','Renuncia','2019-02-06 17:33:14','2019-02-13 20:34:15',NULL,'text_8'),
	 (157,127,'Save','Save','保存','sauvegarder','sparen','Salvare','保存する
','구하다','Сохранить','Salvar','2019-02-06 17:33:14','2019-02-13 20:35:59',NULL,'text_7'),
	 (136,127,'Something doesn''t look right.','Something doesn''t look right.','看起来不对劲。尝试输入你的','Quelque chose ne va pas. Essayez d''entrer votre','Etwas sieht nicht richtig aus.','Qualcosa non sembra giusto. Prova ad inserire il tuo','何かが正しく見えません。あなたの名前を入力してみてください','뭔가 이상하게 보입니다. 귀하의 의견을 입력하십시오','Что-то выглядит не так. Попробуйте ввести свой','Algo no se ve bien. Intenta ingresar tu','2019-01-30 11:07:55','2019-02-14 18:42:52',NULL,'text_5'),
	 (133,132,'Artworks You Saw Today','Artworks You Saw Today','你今天看到的艺术品','Les oeuvres que vous avez vues aujourd''hui','Kunstwerke, die Sie heute gesehen haben','Opere che hai visto oggi','今日見たアートワーク','오늘 보았던 삽화','Работы, которые вы видели сегодня','Obras que viste hoy','2019-01-30 11:07:43','2019-04-18 16:37:29',NULL,'text_1'),
	 (150,111,'Medium','Medium','介质','Moyen','Mittel','medio','中','매질','Средняя','Medio','2019-01-30 21:29:50','2019-07-12 15:49:44',NULL,'text_6'),
	 (164,111,'In This Room','IN THIS ROOM','在这个房间里','DANS CETTE CHAMBRE','IN DIESEM RAUM','IN QUESTA STANZA','この部屋で','이 방에서','В ЭТОЙ КОМНАТЕ','EN ÉSTA HABITACIÓN','2019-07-11 15:27:36','2019-07-17 17:07:54',NULL,'text_11'),
	 (103,NULL,'Welcome_screen','Welcome_screen','','','','','','','','','2019-01-30 11:07:43','2019-01-30 11:07:43',1,'');
INSERT INTO public.translations (id,parent_id,screen_text,english_translation,chinese_translation,french_translation,german_translation,italian_translation,japanese_translation,korean_translation,russian_translation,spanish_translation,created_at,updated_at,display_order,unique_identifier) VALUES
	 (107,NULL,'Visit_soon','Visit_soon','','','','','','','','','2019-01-30 11:07:43','2019-01-30 11:07:43',2,''),
	 (111,NULL,'Result_page','Result_page','','','','','','','','','2019-01-30 11:07:43','2019-01-30 11:07:43',3,''),
	 (114,NULL,'Result_page_Language_Selector','Result_page_Language_Selector','','','','','','','','','2019-01-30 11:07:43','2019-01-30 11:07:43',4,''),
	 (124,NULL,'No_Result_page','No_Result_page','','','','','','','','','2019-01-30 11:07:43','2019-01-30 11:07:43',5,''),
	 (127,NULL,'Bookmark_capture','Bookmark_capture','','','','','','','','','2019-01-30 11:07:43','2019-01-30 11:07:43',6,''),
	 (132,NULL,'Email','Email','','','','','','','','','2019-01-30 11:07:43','2019-01-30 11:07:43',101,''),
	 (137,NULL,'About','About','','','','','','','','','2019-01-30 11:07:55','2019-01-30 11:07:55',7,''),
	 (142,NULL,'UnSupported_OS_Browser_Screen','UnSupported_OS_Browser_Screen','','','','','','','','','2019-01-30 11:08:03','2019-01-30 11:08:03',8,''),
	 (145,NULL,'Orientation_Error_Screen','Orientation_Error_Screen','','','','','','','','','2019-01-30 11:08:12','2019-01-30 11:08:12',9,''),
	 (129,127,'Email address','Email address','电子邮件地址','Adresse électronique','E-Mail-Addresse','Indirizzo email','電子メールアドレス','이메일 주소','Адрес электронной почты','Dirección de correo electrónico','2019-01-30 11:07:43','2019-02-05 19:31:10',NULL,'text_2');
INSERT INTO public.translations (id,parent_id,screen_text,english_translation,chinese_translation,french_translation,german_translation,italian_translation,japanese_translation,korean_translation,russian_translation,spanish_translation,created_at,updated_at,display_order,unique_identifier) VALUES
	 (144,142,'We''re sorry, the version of iOS on your iPhone is not supported.','We''re sorry, the version of iOS on your iPhone is not supported.','很抱歉，您的iPhone上的iOS版本不受支持。','Nous sommes désolés, la version d''iOS sur votre iPhone n''est pas prise en charge.','Die Version von iOS auf Ihrem iPhone wird nicht unterstützt.','Siamo spiacenti, la versione di iOS sul tuo iPhone non è supportata.','申し訳ありませんが、iPhoneのiOSのバージョンはサポートされていません。','죄송합니다. iPhone의 iOS 버전은 지원되지 않습니다.','К сожалению, версия iOS на вашем iPhone не поддерживается.','Lo sentimos, la versión de iOS en tu iPhone no es compatible.','2019-01-30 11:08:03','2019-02-06 14:03:55',NULL,'text_2'),
	 (109,107,'Please come visit us soon.','Please come visit us soon.','请尽快访问我们。','Sil vous plaît venez nous rendre visite bientôt.','Bitte besuchen Sie uns bald.','Per favore, vieni a trovarci presto.','すぐにお越しください。','곧 우리를 방문하십시오.','Пожалуйста, приходите к нам в ближайшее время.','Por favor venga a visitarnos pronto.','2019-01-30 11:07:43','2019-02-05 16:59:49',NULL,'text_2'),
	 (147,111,'Artist','Artist','艺术家','Artiste','Künstler','Artista','アーティスト','예술가','художник','Artista','2019-01-30 21:29:50','2019-02-05 17:20:12',NULL,'text_3'),
	 (115,114,'English','English','英语','Anglais','Englisch','Inglese','英語','영어','английский','Inglés','2019-01-30 11:07:43','2019-02-05 18:49:05',NULL,'text_1'),
	 (110,107,'Visit us online','Visit us online','在线访问我们','Visitez nous en ligne','Besuchen Sie uns online','Visitaci online','私達をオンラインで訪問しなさい','온라인 방문','Посетите нас онлайн','Visitanos en linea','2019-01-30 11:07:43','2019-02-05 17:06:56',NULL,'text_3'),
	 (148,111,'Title','Title','标题','Titre','Titel','Titolo','タイトル','표제','заглавие','Título','2019-01-30 21:29:50','2019-02-05 17:22:26',NULL,'text_4'),
	 (149,111,'Date','Date','日期','Date','Datum','Data','日付','날짜','Дата','Fecha','2019-01-30 21:29:50','2019-02-05 17:24:32',NULL,'text_5'),
	 (151,111,'Dimensions','Dimensions','外形尺寸','Dimensions','Maße','Dimensioni','寸法','치수','Размеры','Dimensiones','2019-01-30 21:29:50','2019-02-05 18:36:58',NULL,'text_7'),
	 (112,111,'Share','Share','分享','Partager','Aktie','Condividere','シェア','몫','Поделиться','Compartir','2019-01-30 11:07:43','2019-02-05 18:40:09',NULL,'text_1'),
	 (116,114,'Español','Spanish','西班牙语','Espagnol','Spanisch','spagnolo','スペイン語','스페인어','испанский','Español','2019-01-30 11:07:43','2019-02-05 18:52:20',NULL,'text_2');
INSERT INTO public.translations (id,parent_id,screen_text,english_translation,chinese_translation,french_translation,german_translation,italian_translation,japanese_translation,korean_translation,russian_translation,spanish_translation,created_at,updated_at,display_order,unique_identifier) VALUES
	 (117,114,'Français','French','法国','Français','Französisch','Francese','フランス語','프랑스의','французский','francés','2019-01-30 11:07:43','2019-02-05 18:58:10',NULL,'text_3'),
	 (118,114,'Deutsch','German','德国','allemand','Deutsch','tedesco','ドイツ語','독일의','немецкий','alemán','2019-01-30 11:07:43','2019-02-05 19:00:01',NULL,'text_4'),
	 (120,114,'Русский','Russian','俄','Russe','Russisch','russo','ロシア語','러시아어','Русский','Ruso','2019-01-30 11:07:43','2019-02-05 19:05:30',NULL,'text_6'),
	 (122,114,'日本語','Japanese','日本','Japonais','Japanisch','giapponese','日本語','일본어','японский','Japoneses','2019-01-30 11:07:43','2019-02-05 19:10:05',NULL,'text_8'),
	 (138,137,'About','About','关于','Sur','Über','Di','約','약','Около','Acerca de','2019-01-30 11:07:55','2019-02-05 20:50:59',NULL,'text_1'),
	 (140,137,'Version 2.0','Version 2.0','版本2.0','Version 2.0','Version 2.0','Versione 2.0','バージョン2.0',' 버전 2.0','Версия 2.0','Versión 2.0','2019-01-30 11:07:55','2019-02-05 20:56:46',NULL,'text_3'),
	 (141,137,'Terms & Conditions','Terms & Conditions','条款','termes','Bedingungen','condizioni','条項','자귀','термины','Condiciones','2019-01-30 11:07:55','2019-02-05 20:58:38',NULL,'text_4'),
	 (108,107,'The Barnes Focus app is meant for use at the Barnes.','The Barnes Focus app is meant for use at the Barnes.','Barnes Focus应用程序适用于Barnes。','L''application Barnes Focus est destinée à être utilisée à Barnes.','Die Barnes Focus App ist für die Verwendung in Barnes bestimmt.','L''app Barnes Focus è pensata per essere utilizzata a Barnes.','バーンズフォーカスアプリはバーンズで使用するためのものです。','Barnes Focus 앱은 Barnes에서 사용하기위한 앱입니다.','Приложение Barnes Focus предназначено для использования в Barnes.','La aplicación Barnes Focus está diseñada para usarse en Barnes.','2019-01-30 11:07:43','2019-02-05 17:10:34',NULL,'text_1'),
	 (113,111,'Also in this Room','Also in this Room','也在这个房间里','Aussi dans cette salle','Auch in diesem Raum','Anche in questa stanza','この部屋でも','이방에서도','Также в этой комнате','Tambien en esta habitacion','2019-01-30 11:07:43','2019-02-05 18:43:15',NULL,'text_2'),
	 (153,127,'Try entering your email again.','Try entering your email again.','重发电邮。','renvoyez un mail.','Geben Sie Ihre E-Mail-Adresse erneut ein.','Email di nuovo.','もう一度メールしてください。','다시 이메일을 보냅니다.','Отправьте письмо снова.','envía un email de nuevo.','2019-01-31 17:59:42','2019-02-14 18:42:18',NULL,'text_6');
INSERT INTO public.translations (id,parent_id,screen_text,english_translation,chinese_translation,french_translation,german_translation,italian_translation,japanese_translation,korean_translation,russian_translation,spanish_translation,created_at,updated_at,display_order,unique_identifier) VALUES
	 (119,114,'Italiano','Italian','意大利','Italien','Italienisch','Italiano','イタリア語','이탈리아의','итальянский','Italiano','2019-01-30 11:07:43','2019-02-05 19:03:53',NULL,'text_5'),
	 (121,114,'中文','Chinese','中文','Chinois','Chinesisch','cinese','中文','중문','китайский','Chino','2019-01-30 11:07:43','2019-02-05 19:07:41',NULL,'text_7'),
	 (123,114,'한국어','Korean','朝鲜的','Coréen','Koreanisch','coreano','韓国語','한국어','корейский','Coreano','2019-01-30 11:07:43','2019-02-05 19:13:00',NULL,'text_9'),
	 (126,124,'Use the scan button to','Use the scan button to','扫描按钮专注于','bouton de numérisation pour se concentrer sur un','Scan-Taste zum Fokussieren auf a','pulsante di scansione per concentrarsi su a','に焦点を合わせるためのスキャンボタン','스캔 버튼을 사용하여','кнопка сканирования, чтобы сосредоточиться на','botón de escaneo para centrarse en una','2019-01-30 11:07:43','2019-02-06 16:00:52',NULL,'text_2'),
	 (128,127,'To receive all the artworks you are seeing today, please enter your email address.','To receive all the artworks you are seeing today, please enter your email address.','要收到您今天看到的所有艺术品，请输入您的电子邮件地址。','Pour recevoir toutes les oeuvres que vous voyez aujourd''hui, veuillez entrer votre adresse email.','Um alle Kunstwerke zu erhalten, die Sie heute sehen, geben Sie bitte Ihre E-Mail-Adresse ein.','Per ricevere tutte le opere che vedi oggi, inserisci il tuo indirizzo email.','あなたが今日見ているすべての作品を受け取るためには、あなたのEメールアドレスを入力してください。','오늘 볼 수있는 모든 작품을 받으려면 이메일 주소를 입력하십시오.','Чтобы получить все произведения искусства, которые вы видите сегодня, пожалуйста, введите свой адрес электронной почты.','Para recibir todas las obras de arte que está viendo hoy, ingrese su dirección de correo electrónico.','2019-01-30 11:07:43','2019-07-15 15:50:02',NULL,'text_1'),
	 (130,127,'We will only use your email to send you the links to the works you''ve seen. You won''t be joined to any other list.','We will only use your email to send you the links to the works you''ve seen. You won''t be joined to any other list.','我们只会使用您的电子邮件向您发送您所看到的作品的链接。您不会加入任何其他列表。','Nous n''utiliserons votre courrier électronique que pour vous envoyer les liens vers les œuvres que vous avez vues. Vous ne serez associé à aucune autre liste.','Wir werden Ihre E-Mail-Adresse nur dazu verwenden, Ihnen die Links zu den Arbeiten zu senden, die Sie gesehen haben. Sie werden keiner anderen Liste hinzugefügt.','Utilizzeremo la tua e-mail solo per inviarti i link alle opere che hai visto. Non ti unirai a nessun altro elenco.','私たちはあなたが見た作品へのリンクをあなたに送るためだけにあなたのEメールを使います。あなたは他のどのリストにも参加しません。','우리는 귀하가 본 작품에 대한 링크를 보내기 위해 귀하의 이메일을 사용합니다. 다른 목록에 가입하지 않습니다.','Мы будем использовать вашу электронную почту только для отправки вам ссылок на работы, которые вы видели. Вы не будете включены в любой другой список.','Solo usaremos su correo electrónico para enviarle los enlaces a las obras que ha visto. No estarás unido a ninguna otra lista.','2019-01-30 11:07:43','2019-02-05 19:46:10',NULL,'text_3'),
	 (125,124,'No results found.','No results found.','未找到结果。使用','Aucun résultat trouvé. Utilisez le','Keine Ergebnisse gefunden. Verwenden Sie die','Nessun risultato trovato. Utilizzare il',' 結果が見つかりません。使用','검색 결과가 없습니다. 사용','Результаты не найдены. Использовать','No se han encontrado resultados. Utilizar el','2019-01-30 11:07:43','2019-02-06 16:00:20',NULL,'text_1'),
	 (152,124,'focus on a work of art.','focus on a work of art.','艺术品。','oeuvre d''art.','Kunstwerk','opera d''arte.','芸術作品。','미술품.','произведение искусства.','obra de arte.','2019-01-31 17:59:42','2019-02-06 16:01:15',NULL,'text_3'),
	 (163,127,'Send Me My Scans','Send Me My Scans','发送给我我的扫描','Envoyez-moi mes scans','Senden Sie mir meine Scans','Inviami le mie scansioni','私のスキャンを送ってください','내 스캔 보내기','Отправь мне мои сканы','Envíame mis exploraciones','2019-07-11 15:27:36','2019-07-17 21:18:39',NULL,'text_8'),
	 (131,127,'Thank you. After your visit, look for an email in your inbox with links to all the works of art you''ve seen today.','Thank you. After your visit, look for an email in your inbox with links to all the works of art you''ve seen today.','谢谢。访问后，在收件箱中查找一封电子邮件，其中包含您今天看到的所有艺术作品的链接。','Je vous remercie. Après votre visite, recherchez un courrier électronique dans votre boîte de réception contenant des liens vers toutes les œuvres d''art que vous avez vues aujourd''hui.','Vielen Dank. Suchen Sie nach Ihrem Besuch in Ihrem Posteingang eine E-Mail mit Links zu allen Kunstwerken, die Sie heute gesehen haben.','Grazie. Dopo la tua visita, cerca un''email nella tua casella di posta con i link a tutte le opere d''arte che hai visto oggi.','ありがとうございました。あなたの訪問の後、あなたが今日見たすべての芸術作品へのリンクがあるあなたの受信箱の中のEメールを探しなさい。','고맙습니다. 방문한 후에는받은 편지함에서 오늘 본 예술 작품에 대한 링크가있는 이메일을 찾으십시오.',' Спасибо. После посещения найдите в своем почтовом ящике письмо со ссылками на все произведения искусства, которые вы видели сегодня.','Gracias. Después de su visita, busque un correo electrónico en su bandeja de entrada con enlaces a todas las obras de arte que ha visto hoy.','2019-01-30 11:07:43','2019-02-05 19:51:25',NULL,'text_4');
INSERT INTO public.translations (id,parent_id,screen_text,english_translation,chinese_translation,french_translation,german_translation,italian_translation,japanese_translation,korean_translation,russian_translation,spanish_translation,created_at,updated_at,display_order,unique_identifier) VALUES
	 (139,137,'Barnes Focus was created by the Knight Center for Digital Innovation in Audience Engagement at the Barnes.','Barnes Focus was created by the Knight Center for Digital Innovation in Audience Engagement at the Barnes.','Barnes Focus应用程序由Knight基金会通过Barnes的观众参与Knight数字创新中心慷慨支持。','L''application Barnes Focus est généreusement soutenue par la Knight Foundation par l''intermédiaire du Centre Knight pour l''innovation numérique dans la participation du public au Barnes.','Die Barnes Focus-App wird großzügig von der Knight Foundation durch das Knight Center für digitale Innovation im Publikumsengagement der Barnes unterstützt.','L''app Barnes Focus è generosamente supportata dalla Knight Foundation attraverso il Knight Center for Digital Innovation in Audience Engagement al Barnes.','Barnes FocusアプリはBarnesでのオーディエンスエンゲージメントにおけるデジタルイノベーションのためのナイトセンターを通じてナイト財団によって寛大にサポートされています。','Barnes Focus 앱은 Barnes의 잠재 고객 참여에서 디지털 혁신을위한 기사 센터 (Knight Center for Digital Innovation)를 통해 Knight Foundation의 지원을받습니다.','Приложение Barnes Focus щедро поддерживается Фондом Найта через Центр цифровых инноваций в области привлечения аудитории в Барнсе.','La aplicación Barnes Focus está generosamente respaldada por la Fundación Knight a través del Centro Knight para la Innovación Digital en la Participación de la Audiencia en el Barnes.','2019-01-30 11:07:55','2019-02-06 14:49:10',NULL,'text_2'),
	 (135,103,'Barnes Focus was created by the Knight Center for Digital Innovation in Audience Engagement at the Barnes.','Barnes Focus was created by the Knight Center for Digital Innovation in Audience Engagement at the Barnes.','Barnes Focus由巴恩斯的观众参与数字创新中心创建。','Barnes Focus a été créé par le Centre Knight pour l’innovation numérique dans la participation du public aux Barnes.','Barnes Focus wurde vom Knight Center für digitale Innovation im Engagement von Publikum in Barnes gegründet.','Barnes Focus è stato creato dal Knight Center for Digital Innovation in Audience Engagement al Barnes.','Barnes Focusは、Barnesで開催された、ナイトオーディエンスエンゲージメントデジタルイノベーションセンターによって作成されました。','Barnes Focus는 Barnes의 Audience Engagement 디지털 혁신 센터의 기사 센터에서 제작했습니다.','Barnes Focus был создан Центром цифровых инноваций Knight Engagement в Barnes','Barnes Focus fue creado por el Centro Knight para la Innovación Digital en la Participación del Público en el Barnes.','2019-01-30 11:07:55','2019-02-13 20:32:52',NULL,'text_5'),
	 (158,132,'Stories You Have Unlocked','Stories You Have Unlocked','','','','','','','','','2019-07-05 17:18:02','2019-07-05 17:18:02',NULL,'text_3'),
	 (159,132,'Unlock more stories on your next visit. Get 20% off your next visit.','Unlock more stories on your next visit. Get 20% off your next visit.','','','','','','','','','2019-07-05 17:18:03','2019-07-05 17:18:03',NULL,'text_4'),
	 (160,132,'Promo Code','Promo Code','','','','','','','','','2019-07-05 17:18:03','2019-07-05 17:18:03',NULL,'text_5'),
	 (161,132,'Buy Tickets','Buy Tickets','','','','','','','','','2019-07-05 17:18:03','2019-07-05 17:18:03',NULL,'text_6'),
	 (143,142,'Please use Safari while we work on compatibility with other browsers.','Please use Safari while we work on compatibility with other browsers.','在我们处理与其他浏览器的兼容性时请使用Safari。','Veuillez utiliser Safari pendant que nous travaillons sur la compatibilité avec d''autres navigateurs.','Bitte verwenden Sie Safari, während wir an der Kompatibilität mit anderen Browsern arbeiten.','Si prega di utilizzare Safari mentre lavoriamo sulla compatibilità con altri browser.','他のブラウザとの互換性に取り組んでいる間はSafariを使用してください。','다른 브라우저와 호환되는 동안 Safari를 사용하십시오.','Пожалуйста, используйте Safari, пока мы работаем над совместимостью с другими браузерами.','Utilice Safari mientras trabajamos en la compatibilidad con otros navegadores.','2019-01-30 11:08:03','2019-02-06 14:02:00',NULL,'text_1'),
	 (146,145,'This app is best viewed in Portrait mode.','This app is best viewed in Portrait mode.','此应用程序最好以纵向模式查看。','Cette application est optimisée en mode Portrait.','Diese App wird am besten im Portrait-Modus angezeigt.','Questa app è ottimizzata per la visualizzazione in modalità verticale.','このアプリは、縦向きモードで最もよく見られます。','이 응용 프로그램은 세로 모드에서 가장 잘 보입니다.','Это приложение лучше всего просматривать в портретном режиме.','Esta aplicación se ve mejor en modo retrato.','2019-01-30 11:08:12','2019-02-06 14:07:46',NULL,'text_1'),
	 (104,103,'Are you at','Are you at',' 你在吗','Êtes-vous à','bist du bei','Sei a','あなたはいますか',' 너 어디 있니','Вы на','¿ Estás en','2019-01-30 11:07:43','2019-02-13 20:33:12',NULL,'text_1'),
	 (156,111,'Please note that not all records are complete as research on the collection is ongoing.','Please note that not all records are complete as research on the collection is ongoing.','请注意，由于对该集合的研究正在进行中，并非所有记录都已完整。','Veuillez noter que tous les enregistrements ne sont pas complets car la recherche sur la collection est en cours.','Bitte beachten Sie, dass nicht alle Aufzeichnungen vollständig sind, da die Erhebung der Sammlung noch läuft.','Si prega di notare che non tutti i registri sono completi poiché la ricerca sulla raccolta è in corso.','コレクションに関する調査が進行中であるため、すべての記録が完全ではないことに注意してください。','수집에 대한 조사가 진행 중이므로 모든 기록이 완전하지는 않습니다.','Обратите внимание, что не все записи являются полными, так как исследование коллекции продолжается.','Tenga en cuenta que no todos los registros están completos, ya que la investigación sobre la colección está en curso.','2019-02-06 17:33:14','2019-02-13 20:35:00',NULL,'text_9');
INSERT INTO public.translations (id,parent_id,screen_text,english_translation,chinese_translation,french_translation,german_translation,italian_translation,japanese_translation,korean_translation,russian_translation,spanish_translation,created_at,updated_at,display_order,unique_identifier) VALUES
	 (134,132,'Thank you for visiting the Barnes today! Here are all the works of art you explored using the Barnes Focus guide. Each link will take you to our collection online for more information about each piece.','Thank you for visiting the Barnes today! Here are all the works of art you explored using the Barnes Focus guide. Each link will take you to our collection online for more information about each piece.','感谢您今天访问巴恩斯！以下是您使用Barnes Focus指南探索的所有艺术作品。每个链接都会带您进入我们的在线收藏集，了解每件作品的更多信息。','Merci d''avoir visité les Barnes aujourd''hui! Voici toutes les œuvres d''art que vous avez explorées à l''aide du guide Barnes Focus. Chaque lien vous mènera à notre collection en ligne pour plus d''informations sur chaque pièce.','Vielen Dank, dass Sie heute die Barnes besucht haben! Hier sind alle Kunstwerke, die Sie mit dem Barnes Focus-Leitfaden erforscht haben. Jeder Link führt Sie online zu unserer Sammlung, um weitere Informationen zu jedem Teil zu erhalten.',' Grazie per aver visitato il Barnes oggi! Ecco tutte le opere d''arte che hai esplorato usando la guida di Barnes Focus. Ogni link ti porterà alla nostra collezione online per ulteriori informazioni su ogni pezzo.','今日Barnesを訪問してくれてありがとう！これが、Barnes Focusガイドを使って調べたすべての芸術作品です。それぞれのリンクは、それぞれの部分についての詳細な情報のためにオンラインで我々のコレクションにあなたを連れて行きます。','오늘 반 즈를 방문해 주셔서 감사합니다! 다음은 Barnes Focus 가이드를 사용하여 탐구 한 모든 예술 작품입니다. 각 링크는 각 작품에 대한 자세한 내용을 보려면 온라인 컬렉션으로 연결됩니다.','Спасибо, что посетили Барнс сегодня! Здесь представлены все произведения искусства, которые вы изучили с помощью руководства Barnes Focus. Каждая ссылка приведет вас в нашу коллекцию онлайн для получения дополнительной информации о каждом произведении.','¡Gracias por visitar el Barnes hoy! Aquí están todas las obras de arte que exploraste usando la guía Barnes Focus. Cada enlace lo llevará a nuestra colección en línea para obtener más información sobre cada pieza.','2019-01-30 11:07:43','2019-04-18 16:38:37',NULL,'text_2'),
	 (162,111,'Culture','Culture','','','','','','','','','2019-07-08 22:13:50','2019-07-08 22:13:50',NULL,'text_10');
